sudo: false
language: node_js
node_js:
  - '10'
  - '11'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/2d86ca6ebe8730048750eeeb3845e8857dc89aa0/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/2d86ca6ebe8730048750eeeb3845e8857dc89aa0/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/2d86ca6ebe8730048750eeeb3845e8857dc89aa0/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/2d86ca6ebe8730048750eeeb3845e8857dc89aa0/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: >-
        ttsjuRo+97H/+iKz19+gGSWOkOSwD/3T4qdoHHXhr1fFpGasq56kc8QmXqCnwlHa5Q5t/Y6ZJj+rHs32LWOxquaavHnqRB+LTvjxcKQPiVqi2+lr+Ki1jOZfl8UtO7vjrc7Hf0nCbTkR0sG5O339ayRXBNZfFLbbNppOv98mLBm2u+eaEVZdC0u+P0tGsrXpEtW9mENiiAlLOAcUcgn0xkoLRsUQk2Wev3KrAOjV4Qhgy8JN3nTfu8Qk5dE2KmfoiCSYzHlh0nSOeeu9LHvirgvgnmsAqCm0saeKwZTs06OmhcY2eBdL3ELLGBdf6Hhr+7lL1T2bWN73pgNVdfLbvTOpgO8kYkd9bMaQ4y/8Dw7xEwtDdIqZHdrUVkAnznMtnKgZ17SxfuFFVEQdkt5ETeflBhQBMQIohoh2DCkxhN1esmhJCNeskFpgbMK0GeGIOkdDSCYFEiu+qO729+3oQGNsQrAV9DY14rsxjIfXSMuBzDOWLQmJXfKVhWXy7gcIt06Y0JPl/iy9oXRzY+Bw6TJ2sttBC450HUJZOCF2huCHo0pc2tmmBZcokUpR0GNRbQQCgDoIoT1eO3VJcGhwcJgs9dn/dm0CiO4i4rEBIdTF72gzOYgwmQdYXYHbJjJEU///+4mwzZ8Hz2mDbgBSYnfLFUrqvODRnMA6iwLgQw4=
