version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      xIeykCkwDp6xVSBrn+Z5ivtrMTtB5qmPWnnMYCZ0jZwF5V4J5SkBF0bz5saIPxD+GC3sT7++m2tCMpiaO5VuAZ28iSRs9vEhmEkP57VUYH/x1NTu/hkR32gTAtmNOYAZyqd/43xkRi/F2kxzH9ObpUHsDzgFzMwcP3/Fvi9zgjdMT9s62SecqDlE2Gp4usg/e6iCrfHnCkDBVg0bnRNQb9kbVnBH61YRYt16Dz7t50+sdVT/cpi0InL/R3lMSEPn+1bfgHTH9a9LVoRq97zhcmFh5Efnq9I5MFLRHk/Y0tXU4l4lcwg1R36VT6NUm1aPuVcCxU7lulCG0zo3lQRk8hZdrye9oT7kYzXTQQNqYGr+RJE+nS1PMSIQOqCCCSpcTBxX/cTJy/TqpWmYbRyZf1Jf4H/omQWW9OnMlwNLUIuZLuIZA4V1KUMwwhpP1qEP0rTQKURkjWXbFQStkca2vqjKXqL1qu0JkJqdEEgquCrZz069uPI8UMhFoZvYM8eH/+4rbFCGCVnWc/a3UfwZkzz7Anrymb0C2BBvKp+wuF/8sDArINhgVWX8FEfoIA7oM71XG1Z1nBfZU04N9mw4Twd75eW5hcsbh/f1wJkJLfmAU8DcDRVuTIjXmUdlZ0iUNPuG2hTMNFl8ST2RO6tF6BTEJwW9U9KlU4Exor5fksE=
