version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      rjROBVXqGAls+RH6QgFrPxg+REOwIbJGNPuTL3owiKGeYKJV7KsrFf7kvWbA+zc9KmkohQnSC+4e2rQe4c3JdQPsYW/kHcSC9Iot2hBnYsovMKuLs4bYPQIfj4Ki2xJMo7YaFzZgdOYaYO1C5IbdrPlOS+2ZuEyFTFtiRKbIj0Bbkc894VfEDFk79V1u7woHkT9wrMT1mR5AqXBkrVNRI3P4hctpzoTUw59BC424WFEbOMZkjJi2n45XggE/Wn/CvoNyYOxcCsrN9GOz5pEP2xYZDerwnBYiL1nN9Ujup5kL8yJtPx1jSlToPoYuQP7RDuEMHpSc384NjGZqoSTbMEIPkIARFbKjS54SvZXEcZFTNm0HelKski0SbEtnXu+Q5NhTYnHxgGkJxlYYsLHVlHCPW9lDuzs5EHqQmgW9QDzGfwNbIdwIe26vtQfREC/UOS7apymSrbTY3bLXPhwdnbMOrS0g7vFqkmgyLVCb0IX9eD+NTXzvcRqpxpZQ3oAbc85u+DDhiP5wAwBh1CRjoQc/kg+vyYn2zM3jnQ1s4JdLLv5EZyPDW2OgSorirkCZAPQws61mC5ZLMjSlTQ9TmfWWbIl1ZQqOsm1TuWrKcc72uxVC5GVSNsLZ40+QT5fR5An7UCTwdpiF6ffPGbzkqk2Uf4j9fW2jfMsaWv/fIys=
