sudo: false
language: node_js
node_js:
- '10'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-publish.bash)"
notifications:
  slack:
    secure: kNhLDJLdGUnX4uyxjz4CUUwaPrdYJC2J92N8mmuLDxrYdCcp7Mju+J3JGFnb2UsgJ+eUm7M4q/we9z0XjQVuIyA2tCJlFEb7U2LtRaQR80NN5729SSAspFb/XAL2LDMJ75avlrL+Ch0027DBGSZgD7ozWbK23m0lL17JmxPEkbZtCAoMOASw8R4+bihSRGxIyEo/DGLD238jm2uEXqPJN3fxZTjU7KiXjfeCXxJ0rdlBuRggdQIt78f3iIc/JjZ2cI+YtexC+7YS+HRtoAW/7qj596K+nVuKUVJOGjWgt3tJ3u+2C+dbOzjWc6vz5MJrTK3bCbF1fKz6UbuCle77B05hpEteuFkhuFtUrLYwJ/KKcN/7eMFKGYpg/RQWN/SOdULd6iRY4h1cGTJt7NXIW1HmiKIWLgiMV0jhIHQ4fhqcGaDO8ykaaNlVHNmWOx+7kP08Dna2VZseSFIs4ruK5Bz235tIrhJb/o7w6eBvlSScvD0xA3C2ycfVLuQLtlaBgwcvcX9vgkTs6/WW2kQsjRk9eyfYLvHDVsbNA31x+HXJtausfAhzNtz9v/RusIQXIvLQK4qFH8kPRnefBT/NVnHW19DmTpjhn+z+Lls6L6dV2YoCrDXxeRutUtKnIBpHwh2SBLKNVs4l3hN+h/lTkQhLX+3dhnY7PXXzR0lNOQI=
  email:
    recipients:
      secure: Im2fxZw7+cOaLzoyDhUUOPLG8HNlPHip5oXhfR0PlTTaTaY98nJ0pGPHDVNZZCnHBxMGwOfwgaZqUKffaM/8OSck39X9vk2Wl2UY7Alrn7YQiJZshBW15cGJBC0M3jHB2b+UNAoRi8IBATuk4hHlQ0LBLAL5bt0rrD6HtMBj6m+DXFFuiQAVquj/Op60AKfaF6teZp2+OxoYVAnAeBQURzWzwQ6SjDcp80p/Hpr4mmtbp9fJHWh4g0JL6PKpZrUTXiqok25zNyE/E+xTuA73q4x8GCmhqe9YkF3acs7C8MKdxIiYS0dSQOTX4DooKg0awcuVsUzFqu6qA67Myp+GI69y5RVQt4SHaDPJI/gfXQQwRmmUoBMc0EyX8vFOyaMo2GdUaq7x/beMUUCQzqSHnMa2mz6rrVbS02IdagfD+19hocNekuJJeX4mwEKzSkQj7VOBSefY4n93WLOzNtRzftv0Z3JRTNYeSmUmBP7YYi1u3vtarGyITzHhjBb7GrdnaaMSOfsmulV9jCJnLPhZK1JE9Q3u72vOISvycCSUdgj8MkIwl3I1CZhScwbis3kFqIf+U3QlS6jmkxaBG2zH80PqccDdvEMPo/nw4hrlsOBx2YpRibXfEn3znKvtvMdFP5OaLf2dsoPPfeRtFi1Kmw0s7n6/wNOrNB/T0kGBAlw=
